/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "gofish_constants.h"

namespace gofish {

const gofishConstants g_gofish_constants;

gofishConstants::gofishConstants() {
}

} // namespace

