/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef gofish_CONSTANTS_H
#define gofish_CONSTANTS_H

#include "gofish_types.h"

namespace gofish {

class gofishConstants {
 public:
  gofishConstants();

};

extern const gofishConstants g_gofish_constants;

} // namespace

#endif
