// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "Initializer.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::gofish;

class InitializerHandler : virtual public InitializerIf {
 public:
  InitializerHandler() {
    // Your initialization goes here
  }

  bool connectToPlayer(const ServerAddress& serverAddress) {
    // Your implementation goes here
    printf("connectToPlayer\n");
  }

  bool setPlayerNum(const int16_t num) {
    // Your implementation goes here
    printf("setPlayerNum\n");
  }

  bool setPrime(const int32_t prime) {
    // Your implementation goes here
    printf("setPrime\n");
  }

  bool sendDeckShares(const std::vector<int32_t> & deckShares) {
    // Your implementation goes here
    printf("sendDeckShares\n");
  }

  bool drawHand(const int16_t numCards) {
    // Your implementation goes here
    printf("drawHand\n");
  }

  int16_t startGame() {
    // Your implementation goes here
    printf("startGame\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<InitializerHandler> handler(new InitializerHandler());
  shared_ptr<TProcessor> processor(new InitializerProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

